version: '3.9'
services:
  backend: 
    build: ./log-fastapi-back
    ports:
      - 5000:5000
    volumes:
      - ./log-fastapi-back/logmanagement:/app
    command: uvicorn logmanagement.app.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - mongodb
    env_file:
      - ./log-fastapi-back/.env
  frontend:
    build: ./log-vue-front/logmanagement
    volumes:
      - './log-vue-front/logmanagement:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
  mongodb:
    image: mongo:4.0.8
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: mongodbpassword
      MONGO_INITDB_DATABASE: logmanagement
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db


volumes:
  mongodbdata: